---
title: "articles included by journal"
author: "meghan forrest"
format: html
editor: visual
---


load packages and data
```{r}
library(readr)
library(tidyverse)
library(rcrossref)

```

You can add options to executable code like this

```{r}
Abstraction_master <- read.csv(file = url("https://raw.githubusercontent.com/meghanrforrest/SPBG-meta-research-study/main/Abstraction_master.csv")) 

screening_decisions <- read.csv(file = url("https://raw.githubusercontent.com/meghanrforrest/SPBG-meta-research-study/main/all_screening-decisions..csv"))
```

Write a function to get the ISSN and eISSN 
```{r}
get_issn_info <- function(doi) {
  metadata <- cr_works(dois = doi)
  issn <- metadata$data$ISSN[1] # Access the first ISSN if there are multiple
  eissn <- metadata$data$`container-title`[1] # Attempt to get EISSN, may need adjustment based on metadata structure
  
  return(list(ISSN = issn, EISSN = eissn))
}
```

```{r}
issn_info <- lapply(Abstraction_master$doi, get_issn_info)

issn_Abstraction_master <- do.call(rbind, 
                                   lapply(issn_info, 
                                          function(x) data.frame(ISSN = x$ISSN, 
                                                                 EISSN = x$EISSN)))

```