---
title: "Supplementary Table 1"
author: "Meghan Forrest"
date: "2023-04-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


data_inc <- read.csv(file = url("https://raw.githubusercontent.com/meghanrforrest/SPBG-meta-research-study/main/included_data.csv"))
```


```{r}
data_inc_table1 <-
  data_inc %>% 
  select(c("doi", "analysis_sample", "neurological_condition_1", "neurological_condition_2", "functional_outcome", "functional_outcome_1", "functional_outcome_2", "functional_outcome_3")) %>% 
  group_by(doi) 


data_inc_table1[data_inc_table1 == ""] <- NA
data_inc_table1[is.na(data_inc_table1)] <- NA

# Relabel any outcome that occurs once to "Other"
data_inc_table1$functional_outcome_1[data_inc_table1$functional_outcome_1 %in% names(which(table(c(data_inc_table1$functional_outcome_1, data_inc_table1$functional_outcome_2, data_inc_table1$functional_outcome_3)) < 3))] = "Other"

data_inc_table1$functional_outcome_2[data_inc_table1$functional_outcome_2 %in% names(which(table(c(data_inc_table1$functional_outcome_1, data_inc_table1$functional_outcome_2, data_inc_table1$functional_outcome_3)) < 3))] = "Other"

data_inc_table1$functional_outcome_3[data_inc_table1$functional_outcome_3 %in% names(which(table(c(data_inc_table1$functional_outcome_1, data_inc_table1$functional_outcome_3, data_inc_table1$functional_outcome_3)) < 3))] = "Other"

# Combine cleaned functional outcomes into one variable  ->  functional_outcomes
data_inc_table1$functional_outcomes <- paste(
  data_inc_table1$functional_outcome_1, 
  data_inc_table1$functional_outcome_2, 
  data_inc_table1$functional_outcome_3)


data_inc_table1$functional_outcomes <-gsub("NA", "", data_inc_table1$functional_outcomes)
table(data_inc_table1$functional_outcomes) # check the output
```


```{r, results = "asis"}
data("table_1_list")
options(qwraps2_markup = "markdown")

# create summary table list
table_1_list <-
  list(
    "Neurological Condition" =
      list(
        "Stroke" = ~ qwraps2::n_perc0(grepl("Stroke", .data$neurologicalconditions) == "TRUE" , show_symbol = TRUE), 
        "Multiple sclerosis" = ~ qwraps2::n_perc0(grepl("Multiple sclerosis", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE), 
        "Parkinson's disease" = ~ qwraps2::n_perc0(grepl("Parkinson's disease", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE), 
        "Encephalitis" = ~ qwraps2::n_perc0(grepl("Encephalitis", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE),
        "Huntington's disease" = ~ qwraps2::n_perc0(grepl("Huntington’s disease", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE),
        "Guillain-Barré" = ~ qwraps2::n_perc0(grepl("Guillain-Barré", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE),
        "TBI" = ~ qwraps2::n_perc0(grepl("TBI", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE),
        "Seizure" = ~ qwraps2::n_perc0(grepl("Seizure", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE),
        "Meningitis" = ~ qwraps2::n_perc0(grepl("Meningitis", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE),
        "Other" = ~ qwraps2::n_perc0(grepl("Other", .data$neurologicalconditions) == "TRUE", show_symbol = TRUE)),
    "Functional Outcome" =
        list(
          "mRS" = ~ qwraps2::n_perc0(grepl("mRS", .data$functional_outcomes) == "TRUE", show_symbol = TRUE), 
          "NIHSS" = ~ qwraps2::n_perc0(grepl("NIHSS", .data$functional_outcomes) == "TRUE", show_symbol = TRUE), 
          "EDSS" = ~ qwraps2::n_perc0(grepl("EDSS", .data$functional_outcomes) == "TRUE", show_symbol = TRUE),
          "UPDRS-III" = ~ qwraps2::n_perc0(grepl("UPDRS-III", .data$functional_outcomes) == "TRUE", show_symbol = TRUE), 
          "Barthel Index" = ~ qwraps2::n_perc0(grepl("Barthel", .data$functional_outcomes) == "TRUE", show_symbol = TRUE),
          "GOS" = ~ qwraps2::n_perc0(grepl("unextended", .data$functional_outcomes) == "TRUE", show_symbol = TRUE), 
          "GOSE" = ~ qwraps2::n_perc0(grepl("GOSE", .data$functional_outcomes) == "TRUE", show_symbol = TRUE),
          "PSOM" = ~ qwraps2::n_perc0(grepl("PSOM", .data$functional_outcomes) == "TRUE", show_symbol = TRUE), 
          "SIS-16" = ~ qwraps2::n_perc0(grepl("SIS-16", .data$functional_outcomes) == "TRUE", show_symbol = TRUE), 
          "Other" = ~ qwraps2::n_perc0(grepl("Other", .data$functional_outcomes) == "TRUE", show_symbol = TRUE)
        ))

# create an object for the overall summary statistics            
table_1_overall <-
  data_inc_table1 %>%
  summary_table(table_1_list)

# create an object for the stratified summary statistics  
table_1_strat <- data_inc_table1 %>%
  group_by(analysis_sample) %>% 
  summary_table(table_1_list)

table_1_complete <-
  cbind(table_1_overall, table_1_strat)

print(table_1_complete)

print(table_1_complete,
      cnames = c("Overall (n = 250)", "Primary (n = 219)", "Secondary (n = 31)"))
```
